"use client";
import Link from "next/link";
import { Bell, Box, Building2, ChevronDown, FolderOpen, Home, Lamp, LayoutTemplate, Library, Menu, MoreHorizontal, Search, Settings, Sparkles, Sofa, User, Wrench } from "lucide-react";
import { useState } from "react";

const categories=[
 {title:"Architecture",desc:"Create house plans, building layouts and 3D architectural models.",img:"/Section/architectresectionone.png",icon:Building2,prompt:"Create a modern 3-bedroom house floor plan."},
 {title:"Interior Design",desc:"Design rooms, styles and materials in 3D.",img:"/Section/section1.png",icon:Lamp,prompt:"Design a modern minimalist living room."},
 {title:"Furniture & Layout",desc:"Plan furniture and optimize available space.",img:"/Section/section0.jpg",icon:Sofa,prompt:"Arrange furniture for this apartment."},
 {title:"3D Visualization",desc:"Create realistic architectural and interior visualizations.",img:"/ai-cards/chat-architecture.svg",icon:Box,prompt:"Create a 3D interior for this floor plan."},
 {title:"Home Robotics",desc:"Design and visualize robots for residential environments.",img:"/ai-cards/agent.svg",icon:Sparkles,prompt:"Design a household robot for a modern home."},
];
const nav=[{label:"Home",icon:Home},{label:"Architecture",icon:Building2},{label:"Interior Design",icon:Lamp},{label:"Furniture & Layout",icon:Sofa},{label:"3D Visualization",icon:Box},{label:"Home Robotics",icon:Sparkles}];
export function DesignDashboard({onOpenStudio}:{onOpenStudio:()=>void}){
 const [prompt,setPrompt]=useState(""); const [menu,setMenu]=useState(false); const [search,setSearch]=useState(false); const [notice,setNotice]=useState(false);
 const submit=()=>{if(!prompt.trim())return; onOpenStudio();};
 return <div className="min-h-screen bg-[#171717] text-zinc-100"><header className="sticky top-0 z-30 flex h-16 items-center border-b border-white/[.08] bg-[#1c1c1c]/95 px-5 backdrop-blur"><div className="flex items-center gap-3"><img src="/logo.png" alt="Crystal" className="h-7 w-7"/><div><b className="text-sm">Crystal</b><span className="ml-2 text-xs text-zinc-500">AI Design Studio</span></div></div><div className="ml-auto flex items-center gap-2"><button aria-label="Search" onClick={()=>setSearch(true)} className="dash-icon"><Search size={18}/></button><button aria-label="Notifications" onClick={()=>setNotice(!notice)} className="dash-icon"><Bell size={18}/></button><button onClick={()=>setMenu(!menu)} className="ml-2 flex items-center gap-2 rounded-xl px-2 py-1.5 hover:bg-white/5"><span className="grid h-7 w-7 place-items-center rounded-full bg-gradient-to-br from-indigo-400 to-violet-500 text-xs font-bold">B</span><span className="hidden text-sm sm:block">Bulzart</span><ChevronDown size={15}/></button>{menu&&<div className="absolute right-5 top-14 w-40 rounded-xl border border-white/10 bg-[#292929] p-1 shadow-2xl"><Link href="/settings" className="flex items-center gap-2 rounded-lg px-3 py-2 text-sm hover:bg-white/10"><Settings size={15}/>Settings</Link><Link href="/login" className="block rounded-lg px-3 py-2 text-sm hover:bg-white/10">Sign out</Link></div>}{notice&&<div className="absolute right-20 top-14 rounded-xl border border-white/10 bg-[#292929] px-4 py-3 text-sm shadow-2xl">You&apos;re all caught up.</div>}</div></header>
 <div className="flex"><aside className="dash-sidebar"><nav>{nav.map(({label,icon:Icon},i)=><button key={label} className={`dash-nav ${i===0?"active":""}`} onClick={()=>i===0?null:onOpenStudio()}><Icon size={18}/>{label}</button>)}</nav><div className="my-5 border-t border-white/[.08]"/><nav><button className="dash-nav" onClick={onOpenStudio}><FolderOpen size={18}/>Projects</button><button className="dash-nav" onClick={onOpenStudio}><Library size={18}/>Design Library</button><button className="dash-nav" onClick={onOpenStudio}><LayoutTemplate size={18}/>Templates</button><button className="dash-nav" onClick={onOpenStudio}><Wrench size={18}/>Tools</button></nav><div className="mt-auto rounded-2xl border border-indigo-400/20 bg-gradient-to-br from-indigo-500/15 to-violet-500/5 p-4"><b className="text-sm">Go Pro</b><p className="mt-2 text-xs leading-5 text-zinc-400">Unlock advanced tools, more AI models and premium features.</p><Link href="/pricing" className="mt-3 block rounded-lg bg-white px-3 py-2 text-center text-xs font-bold text-zinc-900">Upgrade</Link></div><Link href="/settings" className="dash-nav mt-3"><Settings size={18}/>Settings</Link></aside>
 <main className="min-w-0 flex-1 px-5 py-12 lg:px-10"><section className="mx-auto max-w-5xl text-center"><p className="text-xs font-semibold uppercase tracking-[.2em] text-indigo-300">Crystal AI Design Studio</p><h1 className="mt-5 text-4xl font-semibold tracking-[-.05em] sm:text-5xl">Design spaces.<br/><span className="bg-gradient-to-r from-blue-300 via-violet-300 to-fuchsia-300 bg-clip-text text-transparent">Visualize ideas.</span><br/>Build intelligent environments.</h1><p className="mx-auto mt-5 max-w-xl text-sm leading-6 text-zinc-400">Crystal is an AI-powered 3D studio for architecture, interior design, home planning, furniture layout, 3D visualization and home robotics.</p><div className="mt-8 rounded-2xl bg-gradient-to-r from-blue-500 via-violet-500 to-fuchsia-500 p-px shadow-[0_0_32px_rgba(104,91,255,.18)]"><div className="rounded-2xl bg-[#202020] p-2"><label className="sr-only" htmlFor="design-prompt">Describe your design</label><textarea id="design-prompt" value={prompt} onChange={e=>setPrompt(e.target.value)} placeholder="Describe the space or design you want to create..." className="h-20 w-full resize-none bg-transparent p-3 text-sm outline-none placeholder:text-zinc-500"/><div className="flex items-center justify-between gap-2"><Sparkles className="ml-3 text-violet-300" size={17}/><button onClick={submit} disabled={!prompt.trim()} className="rounded-xl bg-[#1687f7] px-4 py-2 text-sm font-semibold disabled:opacity-40">Create</button></div></div></div><div className="mt-3 flex flex-wrap justify-center gap-2">{categories.slice(0,4).map(c=><button key={c.title} onClick={()=>setPrompt(c.prompt)} className="rounded-full border border-white/10 bg-white/[.03] px-3 py-1.5 text-xs text-zinc-300 hover:bg-white/10">{c.title}</button>)}</div></section>
 <section className="mx-auto mt-14 max-w-7xl"><h2 className="text-xl font-semibold">Explore design areas</h2><div className="mt-5 grid gap-4 sm:grid-cols-2 xl:grid-cols-5">{categories.map(c=>{const Icon=c.icon;return <article key={c.title} className="group overflow-hidden rounded-2xl border border-white/[.08] bg-[#212121] transition hover:-translate-y-1 hover:border-white/20"><div className="h-32 overflow-hidden bg-zinc-800"><img src={c.img} alt="" className="h-full w-full object-cover transition duration-500 group-hover:scale-105"/></div><div className="p-4"><Icon size={17} className="text-violet-300"/><h3 className="mt-3 text-sm font-semibold">{c.title}</h3><p className="mt-2 min-h-12 text-xs leading-5 text-zinc-400">{c.desc}</p><button onClick={()=>{setPrompt(c.prompt);window.scrollTo({top:0,behavior:"smooth"})}} className="mt-3 text-xs font-semibold text-blue-300">Explore →</button></div></article>})}</div></section>
 <section className="mx-auto mt-14 max-w-7xl"><div className="flex items-center justify-between"><h2 className="text-xl font-semibold">Recent Projects</h2><button onClick={onOpenStudio} className="text-sm text-blue-300">View all →</button></div><div className="mt-5 grid gap-4 sm:grid-cols-2 xl:grid-cols-5">{["Modern House Design","Living Room Interior","Apartment Plan","Kitchen Design","Home Assistant Robot"].map((name,i)=><button key={name} onClick={onOpenStudio} className="overflow-hidden rounded-2xl border border-white/[.08] bg-[#202020] text-left hover:border-white/20"><img src={categories[i].img} alt="" className="h-28 w-full object-cover"/><div className="p-3"><div className="flex justify-between"><span className="text-[10px] text-violet-300">{categories[i].title}</span><MoreHorizontal size={15}/></div><b className="mt-2 block text-sm">{name}</b><span className="mt-2 block text-[11px] text-zinc-500">Updated {i===0?"2 hours":i===1?"5 hours":"1 day"} ago</span></div></button>)}</div></section></main></div>{search&&<div className="fixed inset-0 z-50 grid place-items-start bg-black/60 p-5 pt-24"><div className="w-full max-w-lg rounded-2xl border border-white/10 bg-[#272727] p-3"><input autoFocus placeholder="Search projects and design tools..." className="w-full bg-transparent p-3 text-sm outline-none"/><button onClick={()=>setSearch(false)} className="px-3 pb-2 text-xs text-zinc-400">Esc to close</button></div></div>}</div>}
