"use client";
import { Box, ChevronDown, Layers3, LoaderCircle, LogOut, PanelLeftClose, User, Zap } from "lucide-react";
import { materials } from "./data";
import type { MaterialName } from "./types";

type Props={material:MaterialName;roughness:number;metallic:number;renderer:string;quality:string;topology:string;texture:string;separateParts:boolean;imageEnhancement:boolean;codeExecution:boolean;estimatedMinutes:number;estimatedCost:number;credits:number;renderLoading:boolean;uploadedImage:string|null;settingsOpen:boolean;onMaterialChange:(v:MaterialName)=>void;onRoughnessChange:(v:number)=>void;onMetallicChange:(v:number)=>void;onRendererChange:(v:string)=>void;onQualityChange:(v:string)=>void;onTopologyChange:(v:string)=>void;onTextureChange:(v:string)=>void;onSeparatePartsChange:(v:boolean)=>void;onImageEnhancementChange:(v:boolean)=>void;onCodeExecutionChange:(v:boolean)=>void;onRender:()=>void;onProfile:()=>void;onSignOut:()=>void;onUpload:(f:File)=>void;onRemoveImage:()=>void;onToggleSettings:()=>void;onCollapse:()=>void};
const clamp=(v:number)=>Math.max(0,Math.min(1,Number.isFinite(v)?v:0));
function Toggle({label,enabled,onChange}:{label:string;enabled:boolean;onChange:(v:boolean)=>void}){return <button type="button" onClick={()=>onChange(!enabled)} aria-pressed={enabled} className="flex h-9 w-full items-center justify-between px-3 text-[11px] focus-visible:outline-[#4A90D9]"><span>{label}</span><span className={`relative h-6 w-12 rounded-full transition ${enabled?"bg-[#4A90D9]":"bg-[#454545]"}`}><i className={`absolute top-1 h-4 w-4 rounded-full bg-white transition-all ${enabled?"left-7":"left-1"}`}/></span></button>}
function Segmented({value,options,onChange}:{value:string;options:string[];onChange:(v:string)=>void}){return <div className="mx-1 grid grid-cols-3 gap-1 rounded-[12px] bg-[#292929] p-1">{options.map(x=><button aria-pressed={value===x} onClick={()=>onChange(x)} key={x} className={`h-7 rounded-lg border text-[9px] transition-all duration-150 focus-visible:outline focus-visible:outline-2 focus-visible:outline-[#4A90D9] ${value===x?"border-[#4A90D9] bg-[#4A90D9] text-white shadow-[0_0_0_2px_rgba(74,144,217,.28),0_3px_9px_rgba(74,144,217,.22)]":"border-transparent bg-[#414141] text-zinc-200 hover:bg-[#4a4a4a]"}`}>{x}</button>)}</div>}
function NumberSlider({label,value,onChange}:{label:string;value:number;onChange:(v:number)=>void}){return <label className="mx-1 mt-2 flex h-8 items-center rounded-[12px] bg-[#292929] px-3 text-[11px]"><b className="flex-1">{label}</b><input aria-label={`${label} slider`} type="range" min="0" max="1" step=".01" value={value} onChange={e=>onChange(clamp(Number(e.target.value)))} className="mr-2 w-20 accent-[#4A90D9]"/><input aria-label={`${label} value`} type="number" min="0" max="1" step=".01" value={value.toFixed(2)} onChange={e=>onChange(clamp(Number(e.target.value)))} className="w-16 rounded-lg bg-[#414141] py-1 text-center outline-none focus:ring-1 focus:ring-[#4A90D9]"/></label>}

export function LeftSidebar(p:Props){return <aside className="crystal-left-panel flex min-h-0 flex-col overflow-hidden border-r border-[#3a3a3a] bg-[#202020] px-2 pb-2 pt-3"><div className="crystal-left-scroll min-h-0 flex-1 overflow-y-auto scrollbar-hide">
 <div className="flex items-center justify-between px-3 pb-3"><h1 className="text-[16px] font-semibold text-zinc-300">Scene Builder</h1><button aria-label="Collapse left panel" onClick={p.onCollapse} className="grid h-9 w-9 place-items-center rounded-[10px] bg-[#4A90D9]"><PanelLeftClose size={18}/></button></div>
 <label className="flex h-12 items-center gap-3 rounded-[14px] bg-[#2c2c2c] px-2"><span className="grid h-9 w-9 place-items-center rounded-[9px] bg-[#4A90D9]"><Layers3 size={20}/></span><select aria-label="Renderer" value={p.renderer} onChange={e=>p.onRendererChange(e.target.value)} className="h-full flex-1 appearance-none bg-transparent text-[12px] font-semibold outline-none">{["Realtime","Path-Traced","Cycles-style"].map(x=><option className="bg-[#292929]" key={x}>{x}</option>)}</select><ChevronDown size={16}/></label>
 <h2 className="px-2 pb-3 pt-6 text-[14px] font-semibold text-zinc-400">Properties</h2><label className="mx-1 flex h-12 items-center rounded-[14px] bg-[#292929] px-4"><span className="text-[12px] font-semibold">Model Quality</span><select aria-label="Model quality" value={p.quality} onChange={e=>p.onQualityChange(e.target.value)} className="ml-auto bg-transparent text-[11px] outline-none">{["Draft","Standard","High","Ultra"].map(x=><option className="bg-[#292929]" key={x}>{x}</option>)}</select></label>
 <h2 className="px-2 pb-3 pt-5 text-[14px] font-semibold text-zinc-300">Material</h2><label className="mx-1 flex h-12 items-center gap-3 rounded-[14px] bg-[#292929] px-2"><span className="grid h-9 w-9 place-items-center rounded-[9px] bg-[#4A90D9]"><Box size={20}/></span><select aria-label="Material" value={p.material} onChange={e=>p.onMaterialChange(e.target.value as MaterialName)} className="h-full flex-1 appearance-none bg-transparent text-[12px] font-semibold outline-none">{materials.map(x=><option className="bg-[#292929]" key={x}>{x}</option>)}</select><ChevronDown size={15}/></label>
 <NumberSlider label="Roughness" value={p.roughness} onChange={p.onRoughnessChange}/><NumberSlider label="Metallic" value={p.metallic} onChange={p.onMetallicChange}/>
 <h3 className="px-3 pb-2 pt-5 text-[11px]">Topology</h3><Segmented value={p.topology} options={["Auto","Low Poly","Topology"]} onChange={p.onTopologyChange}/><h3 className="px-3 pb-2 pt-4 text-[11px]">Texture</h3><Segmented value={p.texture} options={["None","Standard","PBR"]} onChange={p.onTextureChange}/>
 <h2 className="px-4 pb-2 pt-5 text-[14px] font-semibold text-zinc-400">Advanced</h2><div className="mx-1 rounded-[14px] bg-[#292929] py-1"><Toggle label="Separate Parts" enabled={p.separateParts} onChange={p.onSeparatePartsChange}/><Toggle label="Image Enhancement" enabled={p.imageEnhancement} onChange={p.onImageEnhancementChange}/><Toggle label="Code Execution" enabled={p.codeExecution} onChange={p.onCodeExecutionChange}/></div></div>
 <div className="crystal-left-footer shrink-0"><a href="/pricing" className="mt-2 block px-2 text-[10px] leading-4 text-zinc-400 hover:text-[#4A90D9]">Pro workspace: unlimited renders,<br/>industrial-grade mesh export</a><div className="mx-1 mt-2 rounded-[14px] bg-[#292929] p-2"><div className="mb-2 flex justify-center gap-4 text-[12px] font-semibold"><span>{p.estimatedMinutes} min</span><span className="flex items-center gap-1"><Zap size={17} fill="white"/>{p.estimatedCost}</span></div><button disabled={p.renderLoading||p.credits<p.estimatedCost} onClick={p.onRender} className="flex h-9 w-full items-center justify-between rounded-[11px] bg-gradient-to-r from-[#1698f7] to-[#0754ff] px-8 text-[12px] font-semibold disabled:opacity-40">{p.renderLoading?<><LoaderCircle className="animate-spin" size={15}/>Submitting</>:<>Render Queue <span>{p.estimatedCost}</span></>}</button></div><div className="mt-2 flex h-12 items-center rounded-[12px] bg-[#292929] px-2"><button aria-label="Open user menu" onClick={p.onProfile} className="grid h-8 w-8 place-items-center rounded-[8px] bg-[#4A90D9]"><User size={15}/></button><button onClick={p.onSignOut} className="ml-auto flex items-center gap-2 px-3 text-[11px]"><LogOut size={19}/>Sign Out</button></div></div>
 </aside>}
