"use client";
import { Box, ChevronDown, Layers3, LoaderCircle, LogOut, PanelLeftClose, Sparkles, Upload, User, Zap } from "lucide-react";
import { useState } from "react";
import { materials } from "./data";
import type { FloorPlanSettings, MaterialName } from "./types";

type Props={material:MaterialName;roughness:number;metallic:number;renderer:string;quality:string;topology:string;texture:string;separateParts:boolean;imageEnhancement:boolean;codeExecution:boolean;estimatedMinutes:number;estimatedCost:number;credits:number;renderLoading:boolean;uploadedImage:string|null;prompt?:string;loading?:boolean;onPromptChange?:(value:string)=>void;onGenerate?:()=>void;settingsOpen:boolean;floorPlanMode?:boolean;floorPlanSettings?:FloorPlanSettings;onFloorPlanSettingsChange?:(settings:FloorPlanSettings)=>void;onMaterialChange:(v:MaterialName)=>void;onRoughnessChange:(v:number)=>void;onMetallicChange:(v:number)=>void;onRendererChange:(v:string)=>void;onQualityChange:(v:string)=>void;onTopologyChange:(v:string)=>void;onTextureChange:(v:string)=>void;onSeparatePartsChange:(v:boolean)=>void;onImageEnhancementChange:(v:boolean)=>void;onCodeExecutionChange:(v:boolean)=>void;onRender:()=>void;onProfile:()=>void;onSignOut:()=>void;onUpload:(f:File)=>void;onRemoveImage:()=>void;onToggleSettings:()=>void;onCollapse:()=>void};
const clamp=(v:number)=>Math.max(0,Math.min(1,Number.isFinite(v)?v:0));
function Toggle({label,enabled,onChange}:{label:string;enabled:boolean;onChange:(v:boolean)=>void}){return <button type="button" onClick={()=>onChange(!enabled)} aria-pressed={enabled} className="flex h-9 w-full items-center justify-between px-3 text-[11px] focus-visible:outline-[#4A90D9]"><span>{label}</span><span className={`relative h-6 w-12 rounded-full transition ${enabled?"bg-[#4A90D9]":"bg-[#454545]"}`}><i className={`absolute top-1 h-4 w-4 rounded-full bg-white transition-all ${enabled?"left-7":"left-1"}`}/></span></button>}
function Segmented({value,options,onChange}:{value:string;options:string[];onChange:(v:string)=>void}){return <div className="mx-1 grid grid-cols-3 gap-1 rounded-[12px] bg-[#292929] p-1">{options.map(x=><button aria-pressed={value===x} onClick={()=>onChange(x)} key={x} className={`h-7 rounded-lg border text-[9px] transition-all duration-150 focus-visible:outline focus-visible:outline-2 focus-visible:outline-[#4A90D9] ${value===x?"border-[#4A90D9] bg-[#4A90D9] text-white shadow-[0_0_0_2px_rgba(74,144,217,.28),0_3px_9px_rgba(74,144,217,.22)]":"border-transparent bg-[#414141] text-zinc-200 hover:bg-[#4a4a4a]"}`}>{x}</button>)}</div>}
function NumberSlider({label,value,onChange}:{label:string;value:number;onChange:(v:number)=>void}){return <label className="mx-1 mt-2 flex h-8 items-center rounded-[12px] bg-[#292929] px-3 text-[11px]"><b className="flex-1">{label}</b><input aria-label={`${label} slider`} type="range" min="0" max="1" step=".01" value={value} onChange={e=>onChange(clamp(Number(e.target.value)))} className="mr-2 w-20 accent-[#4A90D9]"/><input aria-label={`${label} value`} type="number" min="0" max="1" step=".01" value={value.toFixed(2)} onChange={e=>onChange(clamp(Number(e.target.value)))} className="w-16 rounded-lg bg-[#414141] py-1 text-center outline-none focus:ring-1 focus:ring-[#4A90D9]"/></label>}
function CompactSelect({label,value,options,onChange,icon}:{label?:string;value:string;options:string[];onChange:(value:string)=>void;icon?:React.ReactNode}) {
 const [open,setOpen]=useState(false);
 return <div className="relative min-w-0 flex-1">
  <button type="button" aria-label={label} aria-expanded={open} onClick={()=>setOpen(value=>!value)} className="flex h-full w-full items-center gap-2 rounded-[12px] bg-transparent text-left text-[11px] font-semibold text-zinc-100 transition hover:bg-[#343434]">
   {icon}<span className="min-w-0 flex-1 truncate">{label ? value : value}</span><ChevronDown size={14} className={`shrink-0 text-zinc-400 transition-transform ${open?"rotate-180":""}`}/>
  </button>
  {open&&<div className="absolute left-0 right-0 top-[calc(100%+5px)] z-40 rounded-[12px] bg-[#292929] p-1 shadow-[0_12px_28px_rgba(0,0,0,.4)]">{options.map(option=><button type="button" key={option} onClick={()=>{onChange(option);setOpen(false)}} className={`flex h-8 w-full items-center justify-center rounded-[8px] px-2 text-[11px] transition ${option===value?"bg-[#3a3a3a] text-white":"text-zinc-200 hover:bg-[#343434]"}`}>{option}</button>)}</div>}
 </div>;
}

export function LeftSidebar(p:Props){const floorSettings=p.floorPlanSettings; const updateFloorSettings=(patch:Partial<FloorPlanSettings>)=>{if(floorSettings)p.onFloorPlanSettingsChange?.({...floorSettings,...patch})}; return <aside className="crystal-left-panel crystal-sidebar flex min-h-0 flex-col overflow-visible border-r border-[#292929] bg-[#0F0F0F] px-4 pb-3 pt-5"><div className="crystal-left-scroll min-h-0 flex-1 overflow-y-auto scrollbar-hide">
 <div className="crystal-sidebar-heading flex items-center justify-between px-1 pb-5"><div><span className="crystal-modeling-kicker">CRYSTAL · 3D STUDIO</span><h1 className="text-[17px] font-semibold text-zinc-200">{p.floorPlanMode ? "Scene Builder" : "Modeling"}</h1></div><button type="button" aria-label="Collapse left panel" title="Collapse sidebar" onClick={p.onCollapse} className="grid h-10 w-10 place-items-center rounded-[12px] bg-[#171717] text-zinc-100 transition hover:bg-[#242424]"><PanelLeftClose size={20} strokeWidth={2.4}/></button></div>
 <label className="relative flex h-[54px] items-center gap-3 rounded-[16px] bg-[#2c2c2c] px-3"><span className="grid h-11 w-11 place-items-center rounded-[11px] bg-[#1687f7]"><Layers3 size={22}/></span><CompactSelect label={p.floorPlanMode?"Studio":"Renderer"} value={p.floorPlanMode?"Architectural 2D":p.renderer} options={p.floorPlanMode?["Architectural 2D","Drafting / CAD","Presentation"]:["Realtime","Path-Traced","Cycles-style"]} onChange={p.floorPlanMode?()=>{}:p.onRendererChange}/></label>
 {p.floorPlanMode ? <><h2 className="px-1 pb-4 pt-7 text-[16px] font-semibold text-zinc-400">Drafting setup</h2><div className="space-y-2 rounded-[14px] bg-[#292929] p-2 text-[11px]"><div className="flex items-center justify-between px-2 py-1"><span>Units</span><b className="text-white">{floorSettings?.unit ?? "mm"}</b></div><div className="flex items-center justify-between px-2 py-1"><span>Scale</span><b className="text-white">1 : {floorSettings?.scale ?? 100}</b></div><div className="flex items-center justify-between px-2 py-1"><span>Wall standard</span><b className="text-white">180 mm</b></div></div><h2 className="px-1 pb-3 pt-5 text-[14px] font-semibold text-zinc-300">Snapping</h2><div className="mx-1 rounded-[14px] bg-[#292929] py-1"><Toggle label="Snap to grid" enabled={floorSettings?.snapToGrid ?? true} onChange={snapToGrid=>updateFloorSettings({snapToGrid})}/><Toggle label="Endpoint / midpoint" enabled={floorSettings?.snapToPoints ?? true} onChange={snapToPoints=>updateFloorSettings({snapToPoints})}/><Toggle label="Orthogonal 90°" enabled={floorSettings?.orthogonal ?? true} onChange={orthogonal=>updateFloorSettings({orthogonal})}/></div><h2 className="px-1 pb-3 pt-5 text-[14px] font-semibold text-zinc-300">Drawing standards</h2><Segmented value={p.quality} options={["Draft","Standard","Presentation"]} onChange={p.onQualityChange}/></> : <><div className="crystal-modeling-tabs"><button className="is-active">Modeling</button><button>Shaders</button><button>Render</button></div><div className="crystal-generative-panel"><div className="crystal-panel-label">GENERATIVE 3D</div><label className="crystal-reference-upload"><Upload size={17}/><span>Drag or upload image reference<small>JPG, PNG, WEBP · up to 5MB</small></span><input type="file" accept="image/png,image/jpeg,image/webp" className="sr-only" onChange={event => { const file = event.target.files?.[0]; if (file) p.onUpload(file); event.currentTarget.value = ""; }} /></label><textarea value={p.prompt ?? ""} onChange={event => p.onPromptChange?.(event.target.value)} placeholder="Describe the object you want to generate..." /><div className="crystal-generation-meta"><span>AI Model <b>Precision Mode</b></span><span>Quantity <b>1</b></span></div><button className="crystal-generation-button" disabled={!p.prompt?.trim() || p.loading} onClick={p.onGenerate}><Sparkles size={14}/>{p.loading ? "Generating..." : "Generate 3D Model"}</button></div><h2 className="px-1 pb-4 pt-5 text-[16px] font-semibold text-zinc-400">Properties</h2><label className="relative mx-0 flex h-[54px] items-center rounded-[16px] bg-[#292929] px-4"><span className="text-[13px] font-semibold">Model Quality</span><CompactSelect value={p.quality} options={["Draft","Standard","High","Ultra"]} onChange={p.onQualityChange}/></label>
 <h2 className="px-2 pb-3 pt-5 text-[14px] font-semibold text-zinc-300">Material</h2><label className="relative mx-1 flex h-12 items-center gap-3 rounded-[14px] bg-[#292929] px-2"><span className="grid h-9 w-9 place-items-center rounded-[9px] bg-[#4A90D9]"><Box size={20}/></span><CompactSelect label="Material" value={p.material} options={materials} onChange={value=>p.onMaterialChange(value as MaterialName)}/></label>
 <NumberSlider label="Roughness" value={p.roughness} onChange={p.onRoughnessChange}/><NumberSlider label="Metallic" value={p.metallic} onChange={p.onMetallicChange}/>
 <h3 className="px-3 pb-2 pt-5 text-[11px]">Topology</h3><Segmented value={p.topology} options={["Auto","Low Poly","Topology"]} onChange={p.onTopologyChange}/><h3 className="px-3 pb-2 pt-4 text-[11px]">Texture</h3><Segmented value={p.texture} options={["None","Standard","PBR"]} onChange={p.onTextureChange}/>
 <h2 className="px-4 pb-2 pt-5 text-[14px] font-semibold text-zinc-400">Advanced</h2><div className="mx-1 rounded-[14px] bg-[#292929] py-1"><Toggle label="Separate Parts" enabled={p.separateParts} onChange={p.onSeparatePartsChange}/><Toggle label="Image Enhancement" enabled={p.imageEnhancement} onChange={p.onImageEnhancementChange}/><Toggle label="Code Execution" enabled={p.codeExecution} onChange={p.onCodeExecutionChange}/></div></>}
 </div><div className="crystal-left-footer shrink-0"><a href="/pricing" className="mt-2 block px-2 text-[10px] leading-4 text-zinc-400 hover:text-[#4A90D9]">Pro workspace: unlimited renders,<br/>industrial-grade mesh export</a><div className="mx-1 mt-2 rounded-[14px] bg-[#292929] p-2"><div className="mb-2 flex justify-center gap-4 text-[12px] font-semibold"><span>{p.estimatedMinutes} min</span><span className="flex items-center gap-1"><Zap size={17} fill="white"/>{p.estimatedCost}</span></div><button disabled={p.renderLoading||p.credits<p.estimatedCost} onClick={p.onRender} className="flex h-9 w-full items-center justify-between rounded-[11px] bg-gradient-to-r from-[#1698f7] to-[#0754ff] px-8 text-[12px] font-semibold disabled:opacity-40">{p.renderLoading?<><LoaderCircle className="animate-spin" size={15}/>Submitting</>:<>Render Queue <span>{p.estimatedCost}</span></>}</button></div><div className="mt-2 flex h-12 items-center rounded-[12px] bg-[#292929] px-2"><button aria-label="Open user menu" onClick={p.onProfile} className="grid h-8 w-8 place-items-center rounded-[8px] bg-[#4A90D9]"><User size={15}/></button><button onClick={p.onSignOut} className="ml-auto flex items-center gap-2 px-3 text-[11px]"><LogOut size={19}/>Sign Out</button></div></div>
 </aside>}
