"use client";

import { ChevronDown, CircleHelp, Globe2, Grid3X3, Lightbulb, Link2, LoaderCircle, Send, X, Zap } from "lucide-react";
import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { modelingTools } from "./data";
import { SparkleFilled } from "./filled-icons";
import type { StudioAsset, StudioTool, Transform } from "./types";
import { IconButton } from "./ui";

type Props = { renderer:string; selectedAsset?:StudioAsset; activeTool:StudioTool; prompt:string; loading:boolean; progress:number; error:string|null; transform:Transform; color:string; roughness:number; metallic:number; onToolChange:(v:StudioTool)=>void; onPromptChange:(v:string)=>void; onGenerate:()=>void; onTransformChange:(v:Transform)=>void; onClearError:()=>void; onAssetDrop:(v:string)=>void; onCreateObject:()=>void; onSelectAsset:(id:string)=>void; onColorChange:(v:string)=>void; onOpenPricing:()=>void; onSnapshot:()=>void };
type Camera={yaw:number;pitch:number;distance:number;panX:number;panY:number};
type Point={x:number;y:number};
const cameraStart:Camera={yaw:.74,pitch:.48,distance:12,panX:0,panY:0};
const snapToGrid=(value:number,step=0.5)=>Math.round(value/step)*step;
const shade=(hex:string,n:number)=>{const c=parseInt(hex.slice(1),16),f=(x:number)=>Math.max(0,Math.min(255,Math.round(x*n)));return `rgb(${f(c>>16)},${f((c>>8)&255)},${f(c&255)})`};

function project(point:[number,number,number], camera:Camera, rect:DOMRect) {
  const [x,y,z]=point, cy=Math.cos(camera.yaw), sy=Math.sin(camera.yaw), cp=Math.cos(camera.pitch), sp=Math.sin(camera.pitch);
  const rx=x*cy-z*sy, rz=x*sy+z*cy, ry=y*cp-rz*sp, d=y*sp+rz*cp+camera.distance;
  return { x:rect.width/2+camera.panX+rx*620/d, y:rect.height*.53+camera.panY-ry*620/d, d };
}

function CanvasScene({camera,color,roughness,metallic,grid,selected,face,drawings,measurement,transform}:{camera:Camera;color:string;roughness:number;metallic:number;grid:boolean;selected:boolean;face:number|null;drawings:Point[][];measurement:{a:Point;b:Point}|null;transform:Transform}) {
  const canvas=useRef<HTMLCanvasElement>(null);
  useEffect(()=>{const node=canvas.current;if(!node)return;const draw=()=>{const rect=node.getBoundingClientRect(),ratio=devicePixelRatio,ctx=node.getContext("2d");if(!ctx)return;node.width=rect.width*ratio;node.height=rect.height*ratio;ctx.setTransform(ratio,0,0,ratio,0,0);ctx.fillStyle="#171717";ctx.fillRect(0,0,rect.width,rect.height);
    const line=(a:[number,number,number],b:[number,number,number],stroke:string,width=1)=>{const p1=project(a,camera,rect),p2=project(b,camera,rect);ctx.strokeStyle=stroke;ctx.lineWidth=width;ctx.beginPath();ctx.moveTo(p1.x,p1.y);ctx.lineTo(p2.x,p2.y);ctx.stroke()};
    if(grid){const minorStep=camera.distance>34?2:camera.distance>20?1:camera.distance>10?.5:.25;const majorStep=minorStep*5;const extent=20;const corners=[project([-extent,0,-extent],camera,rect),project([extent,0,-extent],camera,rect),project([extent,0,extent],camera,rect),project([-extent,0,extent],camera,rect)];
      ctx.save();ctx.beginPath();ctx.moveTo(corners[0].x,corners[0].y);corners.slice(1).forEach((corner)=>ctx.lineTo(corner.x,corner.y));ctx.closePath();ctx.fillStyle="rgba(36,38,41,.72)";ctx.fill();ctx.clip();
      for(let n=-extent;n<=extent;n+=minorStep){const rounded=Math.round(n/minorStep)*minorStep,axis=Math.abs(rounded)<.001,major=Math.abs(Math.round(rounded/majorStep)*majorStep-rounded)<.001;const stroke=axis?"#e65353":major?"rgba(185,193,202,.34)":"rgba(135,143,153,.16)";const width=axis?1.7:major?1:.65;line([rounded,0,-extent],[rounded,0,extent],stroke,width);line([-extent,0,rounded],[extent,0,rounded],axis?"#65c466":major?"rgba(185,193,202,.34)":"rgba(135,143,153,.16)",width)}ctx.restore();
    }
    const radians=transform.rotation*Math.PI/180, c=Math.cos(radians), s=Math.sin(radians);
    const v:[number,number,number][]=[[-.5,0,-.5],[.5,0,-.5],[.5,0,.5],[-.5,0,.5],[-.5,1,-.5],[.5,1,-.5],[.5,1,.5],[-.5,1,.5]].map(([x,y,z])=>{const sx=x*transform.scale,sy=y*transform.scale,sz=z*transform.scale;return [sx*c-sz*s+transform.x,sy+transform.y,sx*s+sz*c+(transform.z??0)]});
    const faces=[[0,1,5,4],[1,2,6,5],[2,3,7,6],[3,0,4,7],[4,5,6,7],[3,2,1,0]];
    faces.map((indices,index)=>({indices,index,depth:indices.reduce((sum,j)=>sum+project(v[j],camera,rect).d,0)/indices.length})).sort((a,b)=>b.depth-a.depth).forEach(({indices,index})=>{const pts=indices.map(j=>project(v[j],camera,rect));ctx.beginPath();ctx.moveTo(pts[0].x,pts[0].y);pts.slice(1).forEach(q=>ctx.lineTo(q.x,q.y));ctx.closePath();ctx.fillStyle=face===index?"rgba(22,135,247,.78)":shade(color,[.62,.8,1.04,.5,1.15,.72][index]*(.8+metallic*.2)*(1-roughness*.12));ctx.fill();ctx.strokeStyle=selected?"rgba(74,144,217,.95)":"rgba(235,242,250,.45)";ctx.lineWidth=selected?2:1;ctx.stroke()});
    drawings.forEach(path=>{ctx.strokeStyle="#4A90D9";ctx.lineWidth=2;ctx.beginPath();path.forEach((p,i)=>i?ctx.lineTo(p.x,p.y):ctx.moveTo(p.x,p.y));ctx.stroke()});
    if(measurement){ctx.strokeStyle="#f5c451";ctx.setLineDash([6,4]);ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(measurement.a.x,measurement.a.y);ctx.lineTo(measurement.b.x,measurement.b.y);ctx.stroke();ctx.setLineDash([]);const d=Math.hypot(measurement.b.x-measurement.a.x,measurement.b.y-measurement.a.y)/62;ctx.fillStyle="#f5c451";ctx.font="12px Roboto, sans-serif";ctx.fillText(`${d.toFixed(2)} m`,(measurement.a.x+measurement.b.x)/2+8,(measurement.a.y+measurement.b.y)/2-8)}
  };draw();const observer=new ResizeObserver(draw);observer.observe(node);return()=>observer.disconnect()},[camera,color,roughness,metallic,grid,selected,face,drawings,measurement,transform]);
  return <canvas ref={canvas} aria-label="Interactive 3D perspective grid" className="absolute inset-0 h-full w-full"/>;
}

export function Viewport(p:Props){
  const [camera,setCamera]=useState(cameraStart), drag=useRef<{x:number;y:number;base:Camera;mode:"orbit"|"pan"|"dolly"}|null>(null), transformBase=useRef<Transform|null>(null), objectCreate=useRef<{x:number;y:number;transform:Transform}|null>(null);
  const [mode,setMode]=useState<"Animate"|"Modeling"|"Images">("Modeling"),[chat,setChat]=useState(true),[grid,setGrid]=useState(true),[help,setHelp]=useState(false),[lighting,setLighting]=useState(false),[world,setWorld]=useState(false),[model,setModel]=useState("Precision Mode");
  const [playing,setPlaying]=useState(false),[selected,setSelected]=useState(Boolean(p.selectedAsset)),[face,setFace]=useState<number|null>(null),[drawings,setDrawings]=useState<Point[][]>([]),[drawing,setDrawing]=useState<Point[]|null>(null),[measureStart,setMeasureStart]=useState<Point|null>(null),[measurement,setMeasurement]=useState<{a:Point;b:Point}|null>(null),[history,setHistory]=useState<Transform[]>([]),[future,setFuture]=useState<Transform[]>([]);
  const canvasRef=useRef<HTMLCanvasElement>(null);
  const setView=useCallback((view:string)=>{const presets:Record<string,Partial<Camera>>={Perspective:{yaw:.74,pitch:.48},Top:{yaw:0,pitch:1.52},Front:{yaw:Math.PI,pitch:.02},Right:{yaw:-Math.PI/2,pitch:.02}};setCamera(c=>({...c,...(presets[view]??presets.Perspective),distance:12,panX:0,panY:0}))},[]);
  const toolMode = p.activeTool==="orbit"?"realtime":p.activeTool==="brush"?"draw":p.activeTool==="tools"?"measure":p.activeTool==="model"?"object":p.activeTool==="viewport"?"navigation":p.activeTool;
  const remember=(next:Transform)=>{setHistory(h=>h.length && h[h.length-1]===p.transform ? h : [...h,p.transform].slice(-30));setFuture([]);p.onTransformChange(next)};
  const pointFromEvent=(event:React.PointerEvent)=>{const rect=event.currentTarget.getBoundingClientRect();return{x:event.clientX-rect.left,y:event.clientY-rect.top}};
  const scenePoint=(point:Point)=>{const rect=canvasRef.current?.getBoundingClientRect();if(!rect)return{x:0,y:0};return{x:(point.x-rect.width/2-camera.panX)*camera.distance/620,y:(rect.height*.53+camera.panY-point.y)*camera.distance/620}};
  const cubeFaces=useMemo(()=>{const rect=canvasRef.current?.getBoundingClientRect();if(!rect)return [];const radians=p.transform.rotation*Math.PI/180,c=Math.cos(radians),s=Math.sin(radians);const v:[number,number,number][]=[[-.5,0,-.5],[.5,0,-.5],[.5,0,.5],[-.5,0,.5],[-.5,1,-.5],[.5,1,-.5],[.5,1,.5],[-.5,1,.5]].map(([x,y,z])=>{const sx=x*p.transform.scale,sy=y*p.transform.scale,sz=z*p.transform.scale;return [sx*c-sz*s+p.transform.x,sy+p.transform.y,sx*s+sz*c+(p.transform.z??0)]});return [[0,1,5,4],[1,2,6,5],[2,3,7,6],[3,0,4,7],[4,5,6,7],[3,2,1,0]].map(indices=>indices.map(i=>project(v[i],camera,rect)))},[camera,p.transform]);
  const hitFace=(point:Point)=>cubeFaces.findIndex(poly=>{let inside=false;for(let i=0,j=poly.length-1;i<poly.length;j=i++){const xi=poly[i].x,yi=poly[i].y,xj=poly[j].x,yj=poly[j].y;const intersect=((yi>point.y)!==(yj>point.y))&&point.x<(xj-xi)*(point.y-yi)/(yj-yi)+xi;if(intersect)inside=!inside}return inside});
  const focus=()=>{if(selected){setCamera(c=>({...c,distance:7,panX:0,panY:0}));}};
  const runCommand=()=>{const text=p.prompt.toLowerCase();const number=Number(text.match(/-?\d+(?:\.\d+)?/)?.[0]??"0");if(!number)return false;if(text.includes("move")||text.includes("right")){remember({...p.transform,x:p.transform.x+number});return true}if(text.includes("rotate")){remember({...p.transform,rotation:p.transform.rotation+number});return true}return false};
  useEffect(()=>{const handler=(e:KeyboardEvent)=>{if((e.target as HTMLElement)?.matches("input,textarea,select"))return;const key=e.key.toLowerCase();if(key==="q")p.onToolChange("select");else if(key==="w"||key==="g")p.onToolChange("move");else if(key==="e")p.onToolChange("rotate");else if(key==="s")p.onToolChange("scale");else if(key==="f")focus();else if(e.key==="Escape"){setMeasureStart(null);setDrawing(null);setFace(null);setMeasurement(null)}else if(e.key==="Delete"||e.key==="Backspace"){if(selected){setSelected(false);p.onAssetDrop("")}}else if((e.ctrlKey||e.metaKey)&&key==="z"){e.preventDefault();const previous=history.at(-1);if(previous){setHistory(h=>h.slice(0,-1));setFuture(f=>[p.transform,...f]);p.onTransformChange(previous)}}else if((e.ctrlKey||e.metaKey)&&(key==="y"||(e.shiftKey&&key==="z"))){e.preventDefault();const next=future.at(-1);if(next){setFuture(f=>f.slice(0,-1));setHistory(h=>[...h,p.transform]);p.onTransformChange(next)}}else{const views:Record<string,string>={"1":"Front","3":"Right","7":"Top","0":"Perspective",".":"Perspective"};if(views[e.key])setView(views[e.key])}};window.addEventListener("keydown",handler);return()=>window.removeEventListener("keydown",handler)},[history,future,p.transform,selected,p]);
  useEffect(()=>{if(p.selectedAsset)setSelected(true)},[p.selectedAsset]);
  useEffect(()=>{if(!playing)return;const timer=window.setInterval(()=>p.onTransformChange({...p.transform,rotation:p.transform.rotation+2}),40);return()=>window.clearInterval(timer)},[playing,p.onTransformChange,p.transform]);
  const onPointerDown=(event:React.PointerEvent)=>{if((event.target as HTMLElement).closest("button,input,select,textarea,label"))return;const point=pointFromEvent(event);const cameraMode=event.button===1&&event.ctrlKey?"dolly":event.button===2||event.button===1?"orbit":event.button===0&&event.shiftKey?"pan":null;if(cameraMode){event.preventDefault();event.currentTarget.setPointerCapture(event.pointerId);drag.current={x:event.clientX,y:event.clientY,base:camera,mode:cameraMode};return}if(toolMode==="realtime")return;if(toolMode==="object"){const position=scenePoint(point);const startTransform={x:position.x,y:0,z:position.y,rotation:0,scale:.05};objectCreate.current={x:point.x,y:point.y,transform:startTransform};p.onCreateObject();p.onTransformChange(startTransform);setSelected(true);event.currentTarget.setPointerCapture(event.pointerId);return}if(toolMode==="draw"){setDrawing([point]);event.currentTarget.setPointerCapture(event.pointerId);return}if(toolMode==="measure"){if(!measureStart)setMeasureStart(point);else{setMeasurement({a:measureStart,b:point});setMeasureStart(null)}return}if(toolMode==="scale"){const index=hitFace(point);setFace(index>=0?index:null);setSelected(index>=0||selected);if(index>=0)p.onSelectAsset(p.selectedAsset?.id??"industrial-desk");if(selected){event.currentTarget.setPointerCapture(event.pointerId);transformBase.current=p.transform;drag.current={x:event.clientX,y:event.clientY,base:camera,mode:"pan"}}return}if(toolMode==="select"){const index=hitFace(point);setSelected(index>=0);if(index>=0)p.onSelectAsset(p.selectedAsset?.id??"industrial-desk");else{setFace(null);p.onSelectAsset("")}return}if(toolMode==="move"||toolMode==="rotate"){if(!selected)return;event.currentTarget.setPointerCapture(event.pointerId);transformBase.current=p.transform;drag.current={x:event.clientX,y:event.clientY,base:camera,mode:"pan"};return}};
  const onPointerMove=(event:React.PointerEvent)=>{const point=pointFromEvent(event);if(objectCreate.current){const dx=point.x-objectCreate.current.x,dy=point.y-objectCreate.current.y;const size=Math.max(0.05,Math.min(10,Math.hypot(dx,dy)/62));p.onTransformChange({...objectCreate.current.transform,scale:size});return}if(drawing){setDrawing(path=>path?[...path,point]:path);return}const d=drag.current;if(!d)return;const dx=event.clientX-d.x,dy=event.clientY-d.y;if(toolMode==="move"&&transformBase.current){const worldScale=d.base.distance/620;remember({...transformBase.current,x:snapToGrid(transformBase.current.x+dx*worldScale),z:snapToGrid((transformBase.current.z??0)-dy*worldScale)})}else if(toolMode==="rotate"&&transformBase.current)remember({...transformBase.current,rotation:transformBase.current.rotation+dx*.5});else if(toolMode==="scale"&&transformBase.current)remember({...transformBase.current,scale:Math.max(.1,Math.min(10,transformBase.current.scale-dy*.01))});else if(d.mode==="pan")setCamera({...d.base,panX:d.base.panX+dx,panY:d.base.panY+dy});else if(d.mode==="dolly")setCamera({...d.base,distance:Math.max(2.1,Math.min(42,d.base.distance*Math.exp(dy*.012)))});else setCamera({...d.base,yaw:d.base.yaw-dx*.008,pitch:Math.max(-1.52,Math.min(1.52,d.base.pitch+dy*.007))})};
  const onPointerUp=(event:React.PointerEvent)=>{if(objectCreate.current)objectCreate.current=null;if(drawing){if(drawing.length>1)setDrawings(paths=>[...paths,drawing]);setDrawing(null)}drag.current=null;transformBase.current=null;if(event.currentTarget.hasPointerCapture(event.pointerId))event.currentTarget.releasePointerCapture(event.pointerId)};
  const submit=()=>{if(toolMode==="ai"&&runCommand()){p.onPromptChange("");return}p.onGenerate()};
  return <section ref={canvasRef as React.RefObject<HTMLElement>} className={`relative min-h-0 overflow-hidden bg-[#171717] ${toolMode==="object"||toolMode==="draw"?"cursor-crosshair":toolMode==="move"?"cursor-move":toolMode==="rotate"?"cursor-grab":"cursor-default"}`} onPointerDown={onPointerDown} onPointerMove={onPointerMove} onPointerUp={onPointerUp} onPointerCancel={()=>{objectCreate.current=null;drag.current=null;setDrawing(null)}} onContextMenu={e=>e.preventDefault()} onWheel={e=>{e.preventDefault();setCamera(c=>({...c,distance:Math.max(2.1,Math.min(42,c.distance*Math.exp(e.deltaY*.0012)))}))}} onDragOver={e=>e.preventDefault()} onDrop={e=>{const id=e.dataTransfer.getData("text/asset-id");if(id){p.onAssetDrop(id);setSelected(true)}}}>
    <CanvasScene camera={camera} color={p.color} roughness={p.roughness} metallic={p.metallic} grid={grid} selected={selected} face={face} drawings={drawing?[...drawings,drawing]:drawings} measurement={measurement} transform={p.transform}/><div className="pointer-events-none absolute bottom-5 left-5 rounded-md bg-black/25 px-2 py-1 text-[10px] text-zinc-300">RMB / MMB: orbit · Shift + LMB: pan · Ctrl + MMB: dolly · Wheel: zoom</div>
    <div className="absolute left-1/2 top-2 flex -translate-x-1/2 rounded-[10px] border border-[#343434] bg-[#202020]/95 p-1 shadow-[0_8px_20px_rgba(0,0,0,.18)]">{(["Animate","Modeling","Images"] as const).map(x=><button key={x} onClick={()=>{setMode(x);setChat(true)}} className={`rounded-[8px] border px-5 py-2 text-[11px] transition-colors ${mode===x?"border-[#4A90D9] bg-[#3b3b3b] text-white":"border-transparent text-zinc-500 hover:text-zinc-300"}`}>{x==="Animate"?"Text":x==="Modeling"?"Image":"Multi view"}</button>)}</div>
    <button onClick={()=>setView("Top")} className="absolute right-9 top-5 z-20 h-12 w-12" aria-label="Top view"><span className="absolute left-5 top-5 h-2 w-2 rounded-full border border-[#1687f7]"/><span className="absolute left-6 top-0 h-6 w-[2px] bg-[#e95a55]"/><span className="absolute left-0 top-6 h-[2px] w-6 bg-[#73dc50]"/><span className="absolute left-6 top-6 h-5 w-[2px] bg-[#1687f7]"/></button>
    <div className="absolute right-6 top-[72px] z-20 grid gap-2">{[{I:Lightbulb,l:"Lighting",a:lighting,f:()=>setLighting(v=>!v)},{I:Globe2,l:"World",a:world,f:()=>setWorld(v=>!v)},{I:Grid3X3,l:"Toggle grid",a:grid,f:()=>setGrid(v=>!v)},{I:CircleHelp,l:"Help",a:help,f:()=>setHelp(v=>!v)}].map(({I,l,a,f})=><button key={l} title={l} onClick={f} className={`grid h-10 w-10 place-items-center rounded-[10px] border transition-all ${a?"border-[#4A90D9] bg-[#4A90D9] shadow-[0_0_0_3px_rgba(74,144,217,.35),0_4px_12px_rgba(74,144,217,.25)]":"border-transparent bg-[#252525]"}`}><I size={20}/></button>)}</div>{help&&<div className="absolute right-20 top-[72px] z-30 w-52 rounded-xl border border-white/10 bg-[#242424] p-4 text-xs shadow-2xl">MMB orbits, Shift + MMB pans, wheel zooms. Numpad 1/3/7/0 changes view.</div>}
    <div className={`${chat?"":"hidden"} crystal-ai-prompt absolute bottom-[80px] left-1/2 w-[488px] max-w-[calc(100%_-_32px)] -translate-x-1/2 rounded-[12px] bg-[#202020] px-2 pb-2 pt-1 shadow-[0_12px_28px_rgba(0,0,0,.28)]`}>{selected&&<button type="button" onClick={()=>p.onToolChange("ai")} className="mb-1 flex h-7 w-full items-center gap-2 rounded-[8px] px-2 text-left text-[11px] text-zinc-300 transition hover:bg-[#303030] hover:text-white"><span className="grid h-4 w-4 place-items-center rounded-[4px] bg-[#1687f7] text-[10px] text-white">+</span><span>Ask for changes</span><span className="ml-auto text-[10px] text-zinc-500">Edit object</span></button>}{mode==="Images"&&<div className="crystal-mobile-upgrade"><Zap size={18}/><b>Try Crystal Pro</b><button onClick={p.onOpenPricing}>Pay Now</button></div>}<textarea aria-label="AI model prompt" value={p.prompt} onChange={e=>p.onPromptChange(e.target.value)} onKeyDown={e=>{if((e.ctrlKey||e.metaKey)&&e.key==="Enter")submit()}} placeholder={selected?"Ask for changes to this object":"What do you want to create?"} className="h-[68px] w-full resize-none bg-transparent px-2 py-3 text-[11px] outline-none"/>{p.error&&<div className="flex justify-between text-xs text-red-200"><span>{p.error}</span><button onClick={p.onClearError}><X size={14}/></button></div>}<div className="flex h-10 items-center gap-2"><IconButton icon={Link2} label="Attach reference" className="bg-[#303030]"/><label className="relative flex h-9 items-center rounded-[9px] bg-[#303030] text-[12px]"><select value={model} onChange={e=>setModel(e.target.value)} className="h-full bg-transparent pl-4 pr-9 outline-none"><option>Precision Mode</option><option>Fast Concept</option></select><ChevronDown size={15} className="absolute right-3 top-2"/></label><button disabled={p.loading||!p.prompt.trim()} onClick={submit} className="ml-auto grid h-9 w-9 place-items-center rounded-[9px] bg-[#1687f7]">{p.loading?<LoaderCircle className="animate-spin" size={18}/>:<Send size={18}/>}</button></div></div>
    <div className="crystal-modeling-tools absolute bottom-[18px] left-1/2 flex h-[52px] w-[488px] max-w-[calc(100%_-_32px)] -translate-x-1/2 items-center justify-between rounded-[12px] border border-[#343434] bg-[#202020] px-2 shadow-[0_10px_24px_rgba(0,0,0,.2)]">{modelingTools.slice(0,5).map(t=><IconButton key={t.id} icon={t.icon} label={t.label} active={p.activeTool===t.id} onClick={()=>{p.onToolChange(t.id);if(t.id==="focus")focus();if(t.id==="orbit")setPlaying(v=>!v);if(t.id==="select")setSelected(false)}}/>)}<IconButton icon={SparkleFilled} label="Crystal AI Assistant" active={p.activeTool==="ai"&&chat} onClick={()=>{p.onToolChange("ai");setChat(v=>!v)}}/>{modelingTools.slice(5).map(t=><IconButton key={t.id} icon={t.icon} label={t.label} active={p.activeTool===t.id} onClick={()=>p.onToolChange(t.id)}/>)}</div>
  </section>;
}
