"use client";

import { ChevronDown, CircleHelp, Globe2, Grid3X3, Lightbulb, Link2, LoaderCircle, Send, Sparkles, X, Zap } from "lucide-react";
import { useCallback, useEffect, useRef, useState } from "react";
import { modelingTools } from "./data";
import type { StudioAsset, StudioTool, Transform } from "./types";
import { IconButton } from "./ui";

type Props = { renderer:string; selectedAsset?:StudioAsset; activeTool:StudioTool; prompt:string; loading:boolean; progress:number; error:string|null; transform:Transform; color:string; roughness:number; metallic:number; onToolChange:(v:StudioTool)=>void; onPromptChange:(v:string)=>void; onGenerate:()=>void; onTransformChange:(v:Transform)=>void; onClearError:()=>void; onAssetDrop:(v:string)=>void; onColorChange:(v:string)=>void; onOpenPricing:()=>void; onSnapshot:()=>void };
type Camera={yaw:number;pitch:number;distance:number;panX:number;panY:number};
const cameraStart:Camera={yaw:.74,pitch:.48,distance:12,panX:0,panY:0};
const shade=(hex:string, n:number)=>{const c=parseInt(hex.slice(1),16),f=(x:number)=>Math.max(0,Math.min(255,Math.round(x*n)));return `rgb(${f(c>>16)},${f((c>>8)&255)},${f(c&255)})`};

function CanvasScene({camera,color,roughness,metallic,grid}:{camera:Camera;color:string;roughness:number;metallic:number;grid:boolean}){
  const canvas=useRef<HTMLCanvasElement>(null);
  useEffect(()=>{const node=canvas.current;if(!node)return;const draw=()=>{const rect=node.getBoundingClientRect(),ratio=devicePixelRatio,ctx=node.getContext("2d");if(!ctx)return;node.width=rect.width*ratio;node.height=rect.height*ratio;ctx.scale(ratio,ratio);ctx.fillStyle="#292929";ctx.fillRect(0,0,rect.width,rect.height);const cy=Math.cos(camera.yaw),sy=Math.sin(camera.yaw),cp=Math.cos(camera.pitch),sp=Math.sin(camera.pitch);const point=(x:number,y:number,z:number)=>{const rx=x*cy-z*sy,rz=x*sy+z*cy,ry=y*cp-rz*sp,d=y*sp+rz*cp+camera.distance;return{x:rect.width/2+camera.panX+rx*620/d,y:rect.height*.53+camera.panY-ry*620/d,d}};const line=(a:[number,number,number],b:[number,number,number],color:string,w=1)=>{const p=point(...a),q=point(...b);if(p.d<.1||q.d<.1)return;ctx.beginPath();ctx.moveTo(p.x,p.y);ctx.lineTo(q.x,q.y);ctx.strokeStyle=color;ctx.lineWidth=w;ctx.stroke()};if(grid){for(let i=-40;i<=40;i++){const major=i%5===0;line([i,0,-40],[i,0,40],major?"rgba(135,143,153,.34)":"rgba(110,118,128,.18)");line([-40,0,i],[40,0,i],major?"rgba(135,143,153,.34)":"rgba(110,118,128,.18)")}line([-40,0,0],[40,0,0],"#e65353",1.5);line([0,0,-40],[0,0,40],"#1687f7",1.5)}const v:[number,number,number][]=[[-.5,0,-.5],[.5,0,-.5],[.5,0,.5],[-.5,0,.5],[-.5,1,-.5],[.5,1,-.5],[.5,1,.5],[-.5,1,.5]],faces=[[0,1,5,4],[1,2,6,5],[2,3,7,6],[3,0,4,7],[4,5,6,7]];faces.sort((a,b)=>Math.max(...a.map(i=>point(...v[i]).d))-Math.max(...b.map(i=>point(...v[i]).d))).forEach((face,i)=>{const pts=face.map(j=>point(...v[j]));ctx.beginPath();ctx.moveTo(pts[0].x,pts[0].y);pts.slice(1).forEach(q=>ctx.lineTo(q.x,q.y));ctx.closePath();ctx.fillStyle=shade(color,[.62,.8,1.04,.5,1.15][i]*(.8+metallic*.2)*(1-roughness*.12));ctx.fill();ctx.strokeStyle="rgba(235,242,250,.45)";ctx.stroke()})};draw();const observer=new ResizeObserver(draw);observer.observe(node);return()=>observer.disconnect()},[camera,color,roughness,metallic,grid]);
  return <canvas ref={canvas} aria-label="Interactive 3D perspective grid" className="absolute inset-0 h-full w-full"/>;
}

export function Viewport(p:Props){
  const [camera,setCamera]=useState(cameraStart),drag=useRef<{x:number;y:number;base:Camera;pan:boolean}|null>(null);const [mode,setMode]=useState<"Animate"|"Modeling"|"Images">("Modeling"),[chat,setChat]=useState(true),[grid,setGrid]=useState(true),[help,setHelp]=useState(false),[lighting,setLighting]=useState(false),[world,setWorld]=useState(false),[model,setModel]=useState("Precision Mode");
  const setView=useCallback((view:string)=>{const presets:Record<string,Partial<Camera>>={Perspective:{yaw:.74,pitch:.48},Top:{yaw:0,pitch:1.52},Front:{yaw:Math.PI,pitch:.02},Right:{yaw:-Math.PI/2,pitch:.02}};setCamera(c=>({...c,...(presets[view]??presets.Perspective),distance:12,panX:0,panY:0}))},[]);
  useEffect(()=>{const handler=(e:KeyboardEvent)=>{if((e.target as HTMLElement)?.matches("input,textarea,select"))return;const views:Record<string,string>={"1":"Front","3":"Right","7":"Top","0":"Perspective",".":"Perspective"};if(views[e.key]){e.preventDefault();setView(views[e.key])}};window.addEventListener("keydown",handler);return()=>window.removeEventListener("keydown",handler)},[setView]);
  return <section className="relative min-h-0 overflow-hidden bg-[#292929]" onPointerDown={e=>{if(e.button===1){e.preventDefault();drag.current={x:e.clientX,y:e.clientY,base:camera,pan:e.shiftKey}}}} onPointerMove={e=>{const d=drag.current;if(!d)return;const dx=e.clientX-d.x,dy=e.clientY-d.y;setCamera({...d.base,...(d.pan?{panX:d.base.panX+dx,panY:d.base.panY+dy}:{yaw:d.base.yaw-dx*.008,pitch:Math.max(.08,Math.min(1.52,d.base.pitch+dy*.007))})})}} onPointerUp={()=>drag.current=null} onContextMenu={e=>e.preventDefault()} onWheel={e=>{e.preventDefault();setCamera(c=>({...c,distance:Math.max(2.1,Math.min(42,c.distance*Math.exp(e.deltaY*.0012)))}))}} onDragOver={e=>e.preventDefault()} onDrop={e=>{const id=e.dataTransfer.getData("text/asset-id");if(id)p.onAssetDrop(id)}}>
    <CanvasScene camera={camera} color={p.color} roughness={p.roughness} metallic={p.metallic} grid={grid}/><div className="pointer-events-none absolute bottom-5 left-5 rounded-md bg-black/25 px-2 py-1 text-[10px] text-zinc-300">Wheel: zoom · Middle drag: orbit · Shift + middle drag: pan</div>
    <div className="absolute left-1/2 top-2 flex -translate-x-1/2 rounded-full bg-[#202020]/90 p-1 shadow-xl">{(["Animate","Modeling","Images"] as const).map(x=><button key={x} onClick={()=>{setMode(x);setChat(true)}} className={`rounded-full border px-5 py-2 text-[11px] transition-all ${mode===x?"border-[#4A90D9] bg-[#414141] text-white shadow-[0_0_0_3px_rgba(74,144,217,.35),0_4px_12px_rgba(74,144,217,.25)]":"border-transparent text-zinc-500"}`}>{x}</button>)}</div>
    <button onClick={()=>setView("Top")} className="absolute right-9 top-5 z-20 h-12 w-12" aria-label="Top view"><span className="absolute left-5 top-5 h-2 w-2 rounded-full border border-[#1687f7]"/><span className="absolute left-6 top-0 h-6 w-[2px] bg-[#e95a55]"/><span className="absolute left-0 top-6 h-[2px] w-6 bg-[#73dc50]"/><span className="absolute left-6 top-6 h-5 w-[2px] bg-[#1687f7]"/></button>
    <div className="absolute right-6 top-[72px] z-20 grid gap-2">{[{I:Lightbulb,l:"Lighting",a:lighting,f:()=>setLighting(v=>!v)},{I:Globe2,l:"World",a:world,f:()=>setWorld(v=>!v)},{I:Grid3X3,l:"Toggle grid",a:grid,f:()=>setGrid(v=>!v)},{I:CircleHelp,l:"Help",a:help,f:()=>setHelp(v=>!v)}].map(({I,l,a,f})=><button key={l} title={l} onClick={f} className={`grid h-10 w-10 place-items-center rounded-[10px] border transition-all ${a?"border-[#4A90D9] bg-[#4A90D9] shadow-[0_0_0_3px_rgba(74,144,217,.35),0_4px_12px_rgba(74,144,217,.25)]":"border-transparent bg-[#252525]"}`}><I size={20}/></button>)}</div>{help&&<div className="absolute right-20 top-[72px] z-30 w-52 rounded-xl border border-white/10 bg-[#242424] p-4 text-xs shadow-2xl">MMB orbits, Shift + MMB pans, wheel zooms. Numpad 1/3/7/0 changes view.</div>}
    <div className={`${chat?"":"hidden"} absolute bottom-[80px] left-1/2 w-[488px] max-w-[calc(100%_-_32px)] -translate-x-1/2 rounded-[14px] border border-[#1687f7] bg-[#202020]/95 px-2 pb-2 pt-1 shadow-[0_10px_34px_rgba(0,0,0,.45)]`}>{mode==="Images"&&<div className="crystal-mobile-upgrade"><Zap size={18}/><b>Try Crystal Pro</b><button onClick={p.onOpenPricing}>Pay Now</button></div>}<textarea aria-label="AI model prompt" value={p.prompt} onChange={e=>p.onPromptChange(e.target.value)} onKeyDown={e=>{if((e.ctrlKey||e.metaKey)&&e.key==="Enter")p.onGenerate()}} placeholder="What do you want to create?" className="h-[68px] w-full resize-none bg-transparent px-2 py-3 text-[11px] outline-none"/>{p.error&&<div className="flex justify-between text-xs text-red-200"><span>{p.error}</span><button onClick={p.onClearError}><X size={14}/></button></div>}<div className="flex h-10 items-center gap-2"><IconButton icon={Link2} label="Attach reference" className="bg-[#303030]"/><label className="relative flex h-9 items-center rounded-[9px] bg-[#303030] text-[12px]"><select value={model} onChange={e=>setModel(e.target.value)} className="h-full bg-transparent pl-4 pr-9 outline-none"><option>Precision Mode</option><option>Fast Concept</option></select><ChevronDown size={15} className="absolute right-3 top-2"/></label><button disabled={p.loading||!p.prompt.trim()} onClick={p.onGenerate} className="ml-auto grid h-9 w-9 place-items-center rounded-[9px] bg-[#1687f7]">{p.loading?<LoaderCircle className="animate-spin" size={18}/>:<Send size={18}/>}</button></div></div>
    <div className="crystal-modeling-tools absolute bottom-[18px] left-1/2 flex h-[56px] w-[488px] max-w-[calc(100%_-_32px)] -translate-x-1/2 items-center justify-between rounded-[14px] border border-[#292929] bg-[#202020] px-2">{modelingTools.slice(0,5).map(t=><IconButton key={t.id} icon={t.icon} label={t.label} active={p.activeTool===t.id} onClick={()=>{p.onToolChange(t.id);if(t.id==="focus")setView("Perspective")}}/>)}<IconButton icon={Sparkles} label="AI chat" active={chat} onClick={()=>setChat(v=>!v)}/>{modelingTools.slice(5).map(t=><IconButton key={t.id} icon={t.icon} label={t.label} active={p.activeTool===t.id} onClick={()=>p.onToolChange(t.id)}/>)}</div>
  </section>;
}
