"use client";

import Image from "next/image";
import Link from "next/link";
import type { CSSProperties, ReactNode } from "react";
import { ArrowRight, Download, Layers3, Code2, Cuboid, Sparkles } from "lucide-react";
import { CoreforgePage } from "@/components/cedium-shell";

const categories = ["3D machinery", "Engines", "Automotive", "CAD", "All CAD studios"];
const surfaces = [
  { n: "01", title: "3D Machinery", description: "Engine, transmission, hydraulic, pneumatic, and industrial machinery design in one focused production surface.", Icon: Layers3, href: "/ai-assistant" },
  { n: "02", title: "AI Code Assistant", description: "Generate CAD scripts, simulation helpers, parametric automation, and API integrations for engineering workflows.", Icon: Code2, href: "/workspace/code" },
  { n: "03", title: "CAD Studio Flow", description: "Work across leading CAD studios, CAM tools, and connected 3D production environments.", Icon: Cuboid, href: "/platform/bridges" },
];
function ActionLink({ href, children, secondary = false }: { href: string; children: ReactNode; secondary?: boolean }) { return <Link href={href} className={secondary ? "crystal-button crystal-button-secondary" : "crystal-button"}>{children}</Link>; }
function Feature({ title, copy, image, imageAlt, reverse = false, eyebrow }: { title: string; copy: string; image: string; imageAlt: string; reverse?: boolean; eyebrow: string }) { return <section className={`crystal-feature ${reverse ? "crystal-feature-reverse" : ""}`}><div className="crystal-feature-image"><Image src={image} alt={imageAlt} fill sizes="(max-width: 760px) 100vw, 55vw" /></div><div className="crystal-feature-content"><span className="crystal-eyebrow">{eyebrow}</span><h2>{title}</h2><p>{copy}</p><ActionLink href="/ai-assistant">Explore <ArrowRight size={16} /></ActionLink></div></section>; }
export default function HomePage() { return <CoreforgePage>{(t) => <main className="crystal-home" style={{ "--crystal-fg": t.fg, "--crystal-muted": t.muted } as CSSProperties}>
  <section className="crystal-hero-wrap"><p className="crystal-intro">One AI workspace for machinery, engines, vehicles, CNC, industrial<br className="desktop-break" /> CAD, and engineering code automation.</p><div className="crystal-hero"><div className="crystal-hero-copy"><span className="crystal-eyebrow">Crystal engineering platform</span><h1>Turn Ideas Into Reality</h1><p>We transform complex ideas into intelligent 3D designs, automated systems, and precision-engineered solutions. From concept to CAD, Crystal Studio combines AI, engineering, and advanced visualization to turn ambitious ideas into real-world innovation.</p><div className="crystal-actions"><ActionLink href="/ai-assistant">Launch Studio <ArrowRight size={16} /></ActionLink><ActionLink href="/download" secondary><Download size={16} /> Download App</ActionLink></div></div><div className="crystal-hero-image"><Image src="/roomart.jpg" alt="Futuristic architectural engineering concept" fill priority sizes="(max-width: 760px) 100vw, 54vw" /></div></div><div className="crystal-chips">{categories.map((x) => <span key={x}>{x}</span>)}</div></section>
  <div className="crystal-story"><Feature eyebrow="Immersive design" title="VR Headset VR Goggles" image="/wallpapers/OSwp2.png" imageAlt="VR engineering visual" copy="Explore futuristic engineering concepts through detailed technical drawings, 3D visualizations, specifications, and precision-focused design documentation." /><section className="crystal-platform"><div><span className="crystal-eyebrow">What Crystal Studio does</span><h2>Design, automate, and move into production.</h2></div><p>Bring mechanical systems, vehicle components, CNC workflows, and intelligent CAD automation into one deliberate engineering flow.</p><div className="crystal-surface-grid">{surfaces.map(({ n, title, description, Icon, href }) => <Link key={title} href={href} className="crystal-surface"><span className="crystal-surface-icon"><Icon size={21} /></span><small>/{n}</small><h3>{title}</h3><p>{description}</p><b>Explore <ArrowRight size={14} /></b></Link>)}</div></section><Feature reverse eyebrow="Advanced creation" title="Build Robot Humanoid" image="/wallpapers/OSwp5.png" imageAlt="Humanoid robotics concept" copy="Develop the next generation of intelligent machines with a workspace for robotic systems, precision mechanisms, digital prototyping, and production-ready engineering context." /><section className="crystal-process"><span className="crystal-eyebrow">How it works</span><h2>From concept to engineered output.</h2><div>{[["01", "Start with the machine brief", "Describe the assembly, performance target, geometry, materials, or production requirement."], ["02", "Shape the engineering plan", "Keep CAD context, constraints, assets, and automation organized across the build."], ["03", "Move into production", "Continue into CAD scripting, CAM planning, exports, and review without losing context."]].map(([n, title, copy]) => <article key={n}><b>{n}</b><div><h3>{title}</h3><p>{copy}</p></div></article>)}</div></section><section className="crystal-final"><Sparkles size={18} /><h2>Start in Crystal Studio.</h2><p>Bring your next engineering challenge into a workspace made for ambitious creation.</p><ActionLink href="/main">Open Studio <ArrowRight size={16} /></ActionLink></section></div>
</main>}</CoreforgePage>; }
